// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckphagoaqnpqkaoghcyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrcGhhZ29hcW5wcWthb2doY3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjIwMDEsImV4cCI6MjA2NDQzODAwMX0.LTvKC9mA7hED-JYU5yltvNg8cpbRN5Sy8r-hJ8BClBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);